#!/usr/bin/perl
use strict;
use warnings;


my @numberArray = createArray();
my $count = 0;

foreach ( 0..($#numberArray) ) {
    no warnings "uninitialized";
    $count++ if ( $numberArray[$_] != $numberArray[$_+1] );
}
print "There are $count distinct terms generated by a^b for 2 <= a,b <= 100.\n";

sub createArray {
    my @numberArray = ();
    foreach my $a ( 2..100 ) {
	foreach my $b ( 2..100 ) {
	    push( @numberArray, $a ** $b );
	}
    }
    @numberArray = sort { $a <=> $b } @numberArray;
    return @numberArray;
}
